default: &default_config
  username: "default_username"       # –ó–Ω–∞—á–µ–Ω–∏–µ –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é –¥–ª—è –ª–æ–≥–∏–Ω–∞
  password: "default_password"       # –ó–Ω–∞—á–µ–Ω–∏–µ –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é –¥–ª—è –ø–∞—Ä–æ–ª—è
  folder_tokens: "tokens"            # –ü—É—Ç—å –∫ —Ç–æ–∫–µ–Ω–∞–º —Å–µ—Å—Å–∏–∏
  url: "http://127.0.0.1/"              # URL —Å–∞–π—Ç–∞ hh
  verify_ssl: false                  # –ü—Ä–æ–≤–µ—Ä–∫–∞ SSL
  proxy: null                        # –ü—Ä–æ–∫—Å–∏ (–ø–æ —É–º–æ–ª—á–∞–Ω–∏—é –æ—Ç—Å—É—Ç—Å—Ç–≤—É–µ—Ç)
  black_list_company: []             # –ß–µ—Ä–Ω—ã–π —Å–ø–∏—Å–æ–∫ –∫–æ–º–ø–∞–Ω–∏–π –¥–ª—è —Å–∫–∏–ø–∞ –æ—Ç–∫–ª–∏–∫–∞ (–≤–∑—è—Ç—å –∏–∑ —Å—Å—ã–ª–∫–∏ https://hh.ru/employer/1740)
  black_words: []                    # –ß–µ—Ä–Ω—ã–π —Å–ø–∏—Å–æ–∫ —Å–ª–æ–≤ –¥–ª—è –ø–æ–∏—Å–∫–∞ –≤–∞–∫–∞–Ω—Å–∏–π
  bump_resume: true                  # –ü–æ–¥–Ω–∏–º–∞–µ–º —Ä–µ–∑—é–º–µ –≤ –ø–æ–∏—Å–∫–µ –¥–ª—è —ç–π—á–∞—Ä–æ–≤
  vacancy_find_delay: 14400          # –ó–∞–¥–µ—Ä–∂–∫–∞ –ø–µ—Ä–µ–¥ –ø–æ–∏—Å–∫–æ–º –≤–∞–∫–∞–Ω—Å–∏–π –≤ —Å–µ–∫—É–Ω–¥–∞—Ö (4 —á–∞—Å–∞)
  search: [
    {
      "resume_href": "dd41fba3ff0c4a4ee60039ed1f5a56586a576e",
      "params": {
        "order_by": "publication_time",
        "items_on_page": 100,
        "L_save_area": true,
        "hhtmFrom": "vacancy_search_filter",
        "enable_snippets": true,
        "area": 1,
        "excluded_text": "fullstack",
        "search_field": "name",
        "text": "python senior"
      },
      "letter": "üî•",
    }
    
  ]

dev:
  <<: *default_config                # –ù–∞—Å–ª–µ–¥–æ–≤–∞–Ω–∏–µ –≤—Å–µ—Ö –∑–Ω–∞—á–µ–Ω–∏–π –∏–∑ default
  username: "dev_username"
  password: "dev_password"
  url: "https://hh.ru/"              # URL —Å–∞–π—Ç–∞ hh
  black_list_company: [1740, 3529]
  black_words: ["–º–∏–∫—Ä–æ–∫–æ–Ω—Ç—Ä–æ–ª–ª–µ—Ä", "fullstack"]
  bump_resume: false 